main_app/urls.py
from django.urls import path
from . import views # the '.' refers to referencing from the same folder we are in.

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('flowers/', views.flowers_index, name='index'),
    path('flowers/<int:flower_id>/', views.flowers_detail, name='detail'),
    path('flowers/create/', views.FlowerCreate.as_view(), name='flowers_create'),
    path('flowers/<int:pk>/update/', views.FlowerUpdate.as_view(), name='flowers_update'),
    path('flowers/<int:pk>/delete/', views.FlowerDelete.as_view(), name='flowers_delete'),
    path('flowers/<int:flower_id>/add_sighting/', views.add_sighting, name='add_sighting'),
    # Added Use patterns
    path('flowers/<int:flower_id>/assoc_use/<int:use_id>/', views.assoc_use, name='assoc_use'),
    path('flowers/<int:flower_id>/assoc_use/<int:use_id>/delete/', views.assoc_use_delete, name='assoc_use_delete'),
    path('uses/', views.UseList.as_view(), name='uses_index'),
    path('uses/<int:pk>/', views.UseDetail.as_view(), name='uses_detail'),
    path('uses/create/', views.UseCreate.as_view(), name='uses_create'),
    path('uses/<int:pk>/update/', views.UseUpdate.as_view(), name='uses_update'),
    path('uses/<int:pk>/delete/', views.UseDelete.as_view(), name='uses_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

wild_flower_tn/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('about/', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Use(models.Model):
    name = models.CharField(max_length=50)
    use = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.name}{self.use}'

    def get_absolute_url(self):
        return reverse('uses_detail',
        kwargs={'pk': self.id})


class Flower(models.Model):
    name = models.CharField(max_length=100)
    common_name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    petals = models.IntegerField()
    size = models.IntegerField('Size in Inches')
    leaf_arrangement = models.CharField(max_length=100)
    habitat = models.CharField(max_length=100)
    img = models.CharField(max_length=250)
    uses = models.ManyToManyField(Use)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'flower_id': self.id})

class Sighting(models.Model):
    date = models.DateField('Sighting Date')
    # maybe later add habitat options
    location = models.CharField(max_length=75)

    flower =models.ForeignKey(Flower, on_delete=models.CASCADE)

    def __str__(self):
        return f"Spotted at {self.location} on {self.date}"

main_app/forms.py
from django.forms import ModelForm 
from .models import Sighting 

class SightingForm(ModelForm):
    class Meta:
        model = Sighting 
        fields = ['date', 'location']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Flower, Use
from .forms import SightingForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def flowers_index(request):
    flowers = Flower.objects.filter(user=request.user)
    return render(request, 'flowers/index.html', {'flowers': flowers})

@login_required
def flowers_detail(request, flower_id):
    flower = Flower.objects.get(id=flower_id)
    uses_flower_doesnt_have = Use.objects.exclude(id__in = flower.uses.all().values_list('id'))
    sighting_form = SightingForm()
    return render(request, 'flowers/detail.html', 
    {'flower': flower, 'sighting_form': sighting_form, 'uses': uses_flower_doesnt_have })

@login_required
def add_sighting(request, flower_id):
    form = SightingForm(request.POST)
    if form.is_valid():
        new_sighting = form.save(commit=False)
        new_sighting.flower_id = flower_id
        new_sighting.save()
    return redirect('detail', flower_id=flower_id)

# Many-Many view methods
@login_required
def assoc_use(request, flower_id, use_id):
    Flower.objects.get(id=flower_id).uses.add(use_id)
    return redirect('detail', flower_id=flower_id)

@login_required
def assoc_use_delete(request, flower_id, use_id):
    Flower.objects.get(id=flower_id).uses.remove(use_id)
    return redirect('detail', flower_id=flower_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'

    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

# CUDs Class Views
class FlowerCreate(LoginRequiredMixin, CreateView):
    model = Flower
    fields = ['name', 'common_name', 'type', 'color', 'petals', 'size', 'leaf_arrangement', 'habitat', 'img']
    success_url = '/flowers/'

    def form_valid(self, form):
        form.instsance.user = self.request.user
        return super().form_valid(form)
    
class FlowerUpdate(LoginRequiredMixin, UpdateView):
    model = Flower
    fields = ['name', 'common_name', 'type', 'color', 'petals', 'size', 'leaf_arrangement', 'habitat', 'img']

class FlowerDelete(LoginRequiredMixin, DeleteView):
    model = Flower
    success_url = '/flowers/'

# Use Class Views

class UseList(LoginRequiredMixin, ListView):
    model = Use
    template_name = 'uses/index.html'
class UseDetail(LoginRequiredMixin, DetailView):
    model = Use
    template_name = 'uses/detail.html'
class UseCreate(LoginRequiredMixin, CreateView):
    model = Use
    fields = ['name', 'use']  
class UseUpdate(LoginRequiredMixin, UpdateView):
    model = Use
    fields = ['name', 'use']
class UseDelete(LoginRequiredMixin, DeleteView):
    model = Use
    success_url ='/uses/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %} 
<h1>About</h1>
<p>Collection of Tennessee Wildflowers</p>
<hr/>
<p> Collect and log wildflower details throughout the seasons</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>WildFlower Collector</title>
    <!-- Materialize link for styling -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link
        rel="stylesheet"
        type="text/css"
        href="{% static 'css/style.css' %}"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <!-- classes: navbar-fixed, left brand-logo, nav-wrapper...etc, are a materialized tag -->
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper teal darken-3">
          <ul>
            <li>
              <a href="/" class="left brand-logo"><img src="{% static 'images/WildTennesseeBanner.png' %}" alt="logo" height=64/></a>
            </li>
          </ul>
          <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'flowers_create' %}">Add a Flower</a></li>
            <li><a href="{% url 'index' %}">View All Flowers</a></li>
            <li><a href="{% url 'uses_index' %}">View Flower Tags</a></li>
            <li><a href="{% url 'uses_create' %}">Add New Flower Tag</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <!-- This is where we inject our information. It is a placeholder for objects -->
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer teal darken-3">
      <div class="right">
        All Rights Reserved, &copy; 2022 Wildflower Tennessee &nbsp;
      </div>
    </footer>
  </body>
</html>

main_app/templates/flowers/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Flower Details</h1>
<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ flower.name }}</span>
                <p>Scientific Name: {{ flower.name }}</p>
                <img class="flower-img" src="{{ flower.img }}" alt="{{ flower.common_name }}" height=150px style="border-radius:5px;"/>
                <p>Type: {{ flower.type }}</p>
                <p>Color: {{ flower.color }}</p>
                <p>Petal Number: {{ flower.petal }}</p>
                <p>Size: {{ flower.size }} inches</p>
                <p>Leaf Arrangement: {{ flower.leaf_arrangement }}</p>
                <p>Habitat: {{ flower.habitat }}</p>   
            </div>
            <div class="card-action">
                <a href="{% url 'flowers_update' flower.id %}"><span class="lime-text text-darken-1">Edit</span></a>
                <a href="{% url 'flowers_delete' flower.id %}"><span class="lime-text text-darken-1">Delete</span></a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_sighting' flower.id %}" method="post">
            {% csrf_token %}{{ sighting_form.as_p }}
            <input type="submit" class="btn" value="Add Sighting" />
        </form>
        <table class="striped">
            <thead>
                <tr>
                <th>Sighting Date</th>
                <th>Location</th>
                </tr>
            </thead>
            <tbody>
                {% for sighting in flower.sighting_set.all %}
                <tr>
                <td>{{sighting.date}}</td>
                <td>{{sighting.location}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr />
<div class="row">
    <div class="col s6">
        <h3>{{ flower.name }}'s Tags</h3>
        {% if flower.uses.count %} {% for use in flower.uses.all %}
        <div class="card">
        <div class="card-content">
            <span class="card-title">
                <h4>{{ use.name }}</h4>
                <p>{{ use.use }}</p>
            </span>
        </div>
        </div>
        {% endfor %} {% else %}
        <h5>No Use Tags Added</h5>
        {% endif %}
    </div>
    <!-- Available toys will come after this line -->
    <div class="col s6">
        <h3>Available Use Tags</h3>
        {% if uses.count %}
        {% for use in uses.all %}
            <div class="card">
                <div class="card-content">
                    <span class="card-title">
                        <h4>{{ use.name }}</h4>
                        <p>{{ use.use }}</p>
                    </span>
                </div>
                <div class="card-action">
                    <form action="{% url 'assoc_use' flower.id use.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn">Add</button>
                    </form>
                </div>
            </div>
        {% endfor %}
        {% else %}
            <h5>{{flower.name}} Already Has All Use Tags</h5>
        {% endif %}
    </div> 
</div>
<script>
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    var selectEl = document.getElementById('id_location');
    M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/flowers/index.html
{% extends 'base.html' %} {% block content %}

<h1>Flower List</h1>

{% for flower in flowers %}
<div class="card">
    <a href="{% url 'detail' flower.id %}">
        <div class="card-content">
            <span class="card-title">{{ flower.common_name }}</span>
            <img class="flower-img" src="{{ flower.img }}" alt="{{ flower.common_name }}" height=150px style="border-radius:5px;"/>
            <p>Scientific Name: {{ flower.name }}</p>
            <p>Type: {{ flower.type }}</p>
            <p>Habitat: {{ flower.habitat }}</p>
        </div>
    </a>
</div>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}  
<h1>Home</h1>
{% endblock %}

main_app/templates/main_app/flower_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Flower</h1>

<h4>
    Are you sure you want to delete 
    <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn" />
    <a href="{% url 'detail' flower.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/flower_form.html
{% extends 'base.html' %} {% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Flower</h1>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/main_app/use_confirm_delete.html
{% extends 'base.html' %} {% block content %}

<h1>Delete Use</h1>

<h4>
    Are you sure you want to delete
    <span class="teal-text">{{ object.name }}</span>?
    </h4>

    <form action="" method="post">
    {% csrf_token %}
    <input class="btn red" type="submit" value="Yes - Delete" />
    <a class="btn blue" href="{% url 'detail' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/use_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Update {{ object.name }}</h1>
{% else %}
<h1>Add Tag</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input
        class="btn blue"
        type="submit"
        value="{% if object %} Update Use {% else %} Add Use {% endif %}"
    />
</form>

{% endblock %}

main_app/templates/uses/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Tags Details</h1>

<div class="card">
    <a href="{% url 'uses_detail' use.id %}">
        <div class="card-content">
        < class="card-title"
            >
            <span class="{{ use.name.lower }}-text">{{ use.name }}</span><br/>
            Description:{{use.use}}</span
        >
        </div>
        <div class="card-action">
        <a href="{% url 'uses_update' use.id %}">Edit</a>
        <a href="{% url 'uses_delete' use.id %}">Delete</a>
        </div>
    </a>
</div>

{% endblock %}

main_app/templates/uses/index.html
{% extends 'base.html' %} {% block content %}

<h1>Tags List</h1>

{% for use in object_list %}
<div class="card">
    <a href="{% url 'uses_detail' use.id %}">
        <div class="card-content">
        <span class="card-title"
            >
            <span class="{{use.name}}-text">{{use.name}}</span><br/>
            Description: {{use.use}}</span
        >
        </div>
    </a>
</div>

{% endfor %} {% endblock%}